### PR TITLE
Milestone 1: Basic Project Structure

### PR DESCRIPTION
**Pull request by adamclasic**
- Use create-react-app to initialize a new React app
- Delete any unnecessary file or asset
- Add prop-types using npm
- Add big.js using npm.
- Update Read Me file
- Add linter files
- Deploy app to heroku

### CODE REVIEW

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Changes Required :recycle: 

Hello there! Congratulations for making till here :smile: You have added big.js and prop-types as requested. Before moving on there are some things that need to be done. :100: 

reacterror

- [x]  When I run the local server I faced this error above. Kindly address this issue.

react2

- [x] You haven't deleted the unnecessary documents or assets from your repo. Kindly delete them.

app-deployed

- [x]  You haven't arranged a Readme for this repo, so I can't find the live link. Kindly add this.

Please fix those issues and submit for a re-review when it's finished.
If you have any questions about the review, feel free to reach out to me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by adamclasic** [comment]
fix errors on build
Delete any unnecessary file or asset
Update Read Me file

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please enable GitHub actions and ensure all linting issues are checked and fixed.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Review by mosaaleb — APPROVED** [review]
### Milestone Approved :heavy_check_mark: 

Well done @adamclasic :clap:. You have handled all the requirements in this milestone.
You can merge :+1: 

##### Muhammad Ebeid

**Pull request merged**
